apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-srv
  labels:
    app: auth
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        tke.cloud.tencent.com/networks: "tke-route-eni"
    spec:
      containers:
        - name: auth-srv
          image: hkccr.ccs.tencentyun.com/tke_cluster/tke_cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8889
              protocol: UDP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      nodeSelector:
        environment: dev