apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  annotations:
    service.cloud.tencent.com/direct-access: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: ClientIP
  ports:
    - port: 8889
#      nodePort: 32000
      targetPort: 8889
      protocol: UDP
  #  externalIPs:
  #    - 42.192.43.222
  selector:
    app: auth
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600